/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRoyaltyEngineV1Partial,
  IRoyaltyEngineV1PartialInterface,
} from "../IRoyaltyEngineV1Partial";

const _abi = [
  "function getRoyaltyView(address,uint256,uint256) view returns (address[], uint256[])",
  "function supportsInterface(bytes4) view returns (bool)",
];

export class IRoyaltyEngineV1Partial__factory {
  static readonly abi = _abi;
  static createInterface(): IRoyaltyEngineV1PartialInterface {
    return new utils.Interface(_abi) as IRoyaltyEngineV1PartialInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRoyaltyEngineV1Partial {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IRoyaltyEngineV1Partial;
  }
}
