/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IERC20Partial, IERC20PartialInterface } from "../IERC20Partial";

const _abi = [
  "function allowance(address,address) view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function transfer(address,uint256) returns (bool)",
  "function transferFrom(address,address,uint256) returns (bool)",
];

export class IERC20Partial__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20PartialInterface {
    return new utils.Interface(_abi) as IERC20PartialInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC20Partial {
    return new Contract(address, _abi, signerOrProvider) as IERC20Partial;
  }
}
