/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { NixHelper, NixHelperInterface } from "../NixHelper";

const _abi = [
  "constructor(address)",
  "function getOrders(address,uint256[]) view returns (address[], address[], uint256[][], uint256[], uint256[7][])",
  "function getTokens(uint256[]) view returns (address[], uint256[], uint256[], uint256[], uint256[])",
  "function getTrades(uint256[]) view returns (address[], uint256[], uint256[], tuple(address,uint64)[][])",
  "function nix() view returns (address)",
  "function orderStatus(address,tuple(address,address,uint8,uint8,bytes32,uint256,uint64,uint64,uint64,uint64)) view returns (uint8)",
  "function weth() view returns (address)",
];

export class NixHelper__factory {
  static readonly abi = _abi;
  static createInterface(): NixHelperInterface {
    return new utils.Interface(_abi) as NixHelperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NixHelper {
    return new Contract(address, _abi, signerOrProvider) as NixHelper;
  }
}
